spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # Database
  datasource:
    url: jdbc:mariadb://localhost:3306/langualaxy?useUnicode=true&characterEncoding=utf8
    username: root
    password: qwerty-1
    driver-class-name: org.mariadb.jdbc.Driver
